### ISSUE TITLE
New SAP UI Change as per new roll out

### ISSUE THREAD

**Issue by incpi** [dbeck121/CPI-Helper-Chrome-Extension#172]
As new SAP UI changed,

Which for some users may not be rolled out at the time of writing. Need to look into in sometime, what can be done as alternatively...
listing issues what i noticed,

- [x]  Our top header colour create a issue to see icons clearly. for only 2 colours(black and default =(need to be white / very-light blue may be).. I love to identify environment via header colour as well.
- [x] Popup SAP UI some icon need to change. to much cluttered icons, few look more amazing. 
- [x]  popup default position need to change in y. also we can move to left also, if point 4 is not implemented
- [x] Can we do something to close aside bar navigation to close on start.
- [x] make theme compatible with evening-horizon.
- [x] other colors fix

expecting few design page changes but good so far.
If someone want to do then please feel free to go ahead.

**Comment by fippu82** [comment]
Hi Omkar, not clear to me what you mean (not yet rolled out in my case maybe?). I don't see new changes, except the different menu of SAP on the left (since a few weeks): 
![image](https://github.com/dbeck121/CPI-Helper-Chrome-Extension/assets/14195212/9a6d797d-ba29-43e3-9353-3caaa3f19cef)

But I don't think you mean this as it doesn't affect us. 
Do you have screenshots?

**Comment by incpi** [comment]
Closing this - No action pending.
