### ISSUE TITLE
Question: Statistical Data Collection

### ISSUE THREAD

**Issue by tswymer** [dbeck121/CPI-Helper-Chrome-Extension#72]
Hello,

thank you for creating this tool! 
We are currently evaluating the tool for our own use, and have the following question:

In you [blog post](https://blogs.sap.com/2021/09/02/cpi-cpihelper-chrome-extension-swiss-army-knife-for-integrators/), you mention under the "License and Data Protection" section that you do not collect any data.

Reviewing the source code, we have noticed the "statistic" function in the tools.js file, which makes a call to an aws lambda function, passing some usage data, along with sessionIds.

Could you please elaborate on what data is collected here and potentially update the documentation to include something on data collection, even if it is for statistical purposes?

Many thanks in advance!

**Comment by dbeck121** [comment]
Hi and thanks for the issue,

good point with the documentation. As I am working on CPI Helper in my rare free time, the documentation lacks most of the time behind. I will change that as soon as I have some more time.

I am experimenting with statistical data like how many users are using CPI Helper and what functionality are people using. So I was curious if people really use the plugin engine in CPI Helper and if it is worth to spend more time with the plugin engine or if I should focus more on debugging functionality.

At first I wanted to try sth like Google Analytics but GA does not feel GDPR compliant. So I tried to create my own solution to be sure that no personal data is send.

In summary
- Your tenant name, personal data, urls etc will never be sent from CPI-Helper
- No other personal data is collected
- I collect metrics like how many users access per day and per month because the statistics in Google Chrome about number of installations has nothing to do with how many people are really using the tool.
- I check which plugins you use within CPI-Helper to check which ones are used and to focus on
- I check some other metrics like are you using the trace mode etc.
- There is a session ID that is saved for one day and is created by a random function.
- The data is sent to an AWS lambda function and from there sent to a mysql server hosted by all-inkl.com. It is not stored on AWS.
- The mysql server is the final destination of the data. I have a SQL function that shows me the users per day. I did not have time to do more with the data.

Hope that helps. 

BR
Dominic Beckbauer
