### ISSUE TITLE
JMS

### ISSUE THREAD

**Issue by jonprow** [dbeck121/CPI-Helper-Chrome-Extension#73]
We aren't seeing messages when the iflow has JMS sender

**Comment by fippu82** [comment]
This is a Cloud Integration bug, I believe. It has nothing to do with CPI Helper, because the issue can also be observed in the standard Trace mode. Only the JMS Sender step is available, nothing else after that. 
@dbeck121 Can you confirm this too? I haven't found an explanation yet why this is the case.

**Comment by dbeck121** [comment]
@fippu82 is right. I do not get any data here :(

**Comment by fippu82** [comment]
@dbeck121 What we probably could do is parsing the text log. It contains all the steps which are missing in the standard graphical Trace view.

**Comment by fippu82** [comment]
While working with a JMS sender flow right now, I suddenly realized that there are always two Trace entries under "Runs" in the log. One is empty, but the second one indeed contains the steps! So we should reopen this issue and fix this in one of the next releases, if possible.

**Comment by fippu82** [comment]
#80

**Comment by dbeck121** [comment]
Should be fixed now. Thanks to @fippu82
